# Resolve ProjectSettings.icon by the asset's own GUID so a hand-authored CMakeLists.txt does not
# duplicate a content path. Explicit ICON arguments still take precedence at the call site.
function(gameengine_resolve_project_icon content_directory output_path output_guid)
    set(${output_path} "" PARENT_SCOPE)
    set(${output_guid} "" PARENT_SCOPE)
    set(glob_options)
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set(glob_options CONFIGURE_DEPENDS)
    endif()
    file(GLOB project_files ${glob_options} "${content_directory}/*.gameproject")
    list(LENGTH project_files project_count)
    if(project_count EQUAL 0)
        return()
    elseif(NOT project_count EQUAL 1)
        message(FATAL_ERROR "Project icon resolution requires one .gameproject in ${content_directory}")
    endif()
    list(GET project_files 0 project_file)
    # Track contents as well as the glob: changing an existing icon GUID must regenerate
    # the executable resource even when no file was added or removed.
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${project_file}")
    endif()
    file(READ "${project_file}" project_contents)
    string(JSON project_type ERROR_VARIABLE project_error TYPE "${project_contents}")
    if(project_error OR NOT project_type STREQUAL "OBJECT")
        message(FATAL_ERROR "Could not read project settings from ${project_file}: ${project_error}")
    endif()
    string(JSON icon_type ERROR_VARIABLE icon_error TYPE "${project_contents}" icon)
    if(icon_error)
        return() # The optional icon field was not authored.
    elseif(NOT icon_type STREQUAL "STRING")
        message(FATAL_ERROR "ProjectSettings.icon must be an asset GUID string in ${project_file}")
    endif()
    string(JSON icon_guid GET "${project_contents}" icon)
    if(icon_guid STREQUAL "")
        return()
    endif()
    string(LENGTH "${icon_guid}" guid_length)
    if(NOT guid_length EQUAL 32 OR NOT icon_guid MATCHES "^[0-9a-fA-F]+$")
        message(FATAL_ERROR "ProjectSettings.icon is not a 32-digit asset GUID in ${project_file}")
    endif()
    string(TOLOWER "${icon_guid}" normalized_guid)
    file(GLOB_RECURSE icon_sidecars ${glob_options} "${content_directory}/*.ico.meta")
    set(resolved_icon "")
    set(resolved_guid "")
    foreach(sidecar IN LISTS icon_sidecars)
        if(NOT CMAKE_SCRIPT_MODE_FILE)
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${sidecar}")
        endif()
        file(READ "${sidecar}" sidecar_contents)
        string(JSON candidate_guid ERROR_VARIABLE candidate_error GET "${sidecar_contents}" guid)
        if(candidate_error)
            continue()
        endif()
        string(TOLOWER "${candidate_guid}" normalized_candidate)
        if(NOT normalized_candidate STREQUAL normalized_guid)
            continue()
        endif()
        string(REGEX REPLACE "\\.meta$" "" candidate_icon "${sidecar}")
        if(NOT EXISTS "${candidate_icon}")
            message(FATAL_ERROR "ProjectSettings.icon names a missing .ico asset: ${candidate_icon}")
        endif()
        if(NOT resolved_icon STREQUAL "")
            message(FATAL_ERROR "ProjectSettings.icon GUID occurs in more than one .ico asset: ${icon_guid}")
        endif()
        set(resolved_icon "${candidate_icon}")
        set(resolved_guid "${candidate_guid}")
    endforeach()
    if(resolved_icon STREQUAL "")
        message(FATAL_ERROR "ProjectSettings.icon GUID has no .ico asset in ${content_directory}: ${icon_guid}")
    endif()
    set(${output_path} "${resolved_icon}" PARENT_SCOPE)
    set(${output_guid} "${resolved_guid}" PARENT_SCOPE)
endfunction()
